import '@/app/globals.css'
import Header from '@/components/header';
import { Inter } from "next/font/google";
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'ORM Prisma - Relation N:M',
  description: 'Generated by create next app',
  manifest: '/manifest.json'
}



export default function RootLayout({ children }) {
  return (
    <html lang="es" className='scrollbar-gutter-stable'>
      <body className={`${inter.className} grid min-h-screen grid-rows-[1fr_auto]`}>
        <Header />

        <main className='w-full min-h-0 max-w-6xl mx-auto py-8 px-4 mt-20'>
          {children}
        </main>

        <Footer />
        <Toaster position='top-center' richColors />
      </body>
    </html>
  )
}






const Footer = async () => {
  'use cache'
  return (
    <footer className='flex justify-between px-4 py-2 border-t border-slate-400'>
      <div>  <a href="https://github.com/jamj2000"> &copy; jamj2000 </a> </div>
      <div>  {new Date().getFullYear()} </div>
    </footer>
  )
}

